#ifndef VIDEO_CONSTANTS_H
#define VIDEO_CONSTANTS_H
#define COLOR_BLACK 	0x00
#define COLOR_BLUE 	0x01
#define COLOR_GREEN 	0x02
#define COLOR_CYAN 	0x03
#define COLOR_RED 	0x04
#define COLOR_MAGENTA 	0x05
#define COLOR_BROWN	0x06
#define COLOR_LGREY 	0x07
#define COLOR_DGREY 	0x08
#define COLOR_LBLUE 	0x09
#define COLOR_LGREEN 	0x0A
#define COLOR_LCYAN 	0x0B
#define COLOR_LRED 	0x0C
#define COLOR_LMAGENTA 	0x0D
#define COLOR_LBROWN 	0x0E
#define COLOR_WHITE 	0x0F
#endif
